name: vocably
description: "Vocably is an English dictionary application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  hugeicons: ^0.0.11
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  lottie: ^3.3.1
  audioplayers: ^6.4.0
  animated_text_kit: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
